### ISSUE TITLE
Inconsistent indentation

### ISSUE THREAD

**Issue by MartinHelmut** [mce777/currStyles#4]
You use different styles for indention in you components, e.g.: https://github.com/mce777/currStyles/blob/master/lib/components/molecules/input_dropdown/InputDropdown.js#L9-L18

**Comment by mce777** [comment]
Looking at this in Webstorm and the indentation looks ok. Maybe I'm missing something.

**Comment by MartinHelmut** [comment]
You use sometimes 2 spaces, 4 spaces or 1 tab. This is inconsistency ;)

**Comment by mce777** [comment]
I adjusted the indentations where it made sense to: https://github.com/mce777/currStyles/pull/10
